/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.8
 * Generated at: 2014-06-26 12:40:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import toranoan.OrderServlet;
import toranoan.Item;
import toranoan.Bean;
import java.util.List;
import java.lang.Integer;
import java.util.Iterator;
import java.util.HashMap;
import java.util.regex.*;
import java.text.*;

public final class order_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	// エンコーディング
	response.setContentType("text/html; charset=utf-8");
	request.setCharacterEncoding("utf-8");
	DecimalFormat exFormat = new DecimalFormat("#,###,###,##0");

	HashMap<String,Object> map = new HashMap<String,Object>();
	int amount = 0;

	if((session.getAttribute("ordermap")) != null) {
		map = (HashMap<String,Object>) session.getAttribute("ordermap");
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head><title>出前出張サービス◆虎乃庵◆</title></head>\r\n");
      out.write("<body>\r\n");
      out.write("<form action=\"logout\" method=\"POST\" name=\"logout\">\r\n");
      out.write("\t<input type=\"submit\" value=\"ログアウト\">\r\n");
      out.write("</form>\r\n");
      out.write("<h2>注文内容</h2>\r\n");
      out.write("<table border=\"1\" width=\"500\" cellspacing=\"0\" cellpadding=\"5\" bordercolor=\"#333333\">\r\n");
      out.write("\t<tr bgcolor=\"#EE0000\">\r\n");
      out.write("\t\t<th><font color=\"#FFFFFF\">メニュー</font></th>\r\n");
      out.write("\t\t<th><font color=\"#FFFFFF\">値段</font></th>\r\n");
      out.write("\t\t<th><font color=\"#FFFFFF\">数量</font></th>\r\n");
      out.write("\t\t<th><font color=\"#FFFFFF\">金額</font></th>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");

		Iterator it = map.keySet().iterator();
        while(it.hasNext()){
            Object obj = it.next();
            Item itm = (Item) map.get(obj);
            String id = itm.getId();
            String item = itm.getItem();
            int price = itm.getPrice();
            int volume = itm.getVolume();
            int anamount = price*volume;

      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<p>");
      out.print(item );
      out.write("</p>\r\n");
      out.write("\t\t\t<form action=\"modify\" method=\"POST\">\r\n");
      out.write("\t\t\t<input type=\"button\" name=\"");
      out.print(id );
      out.write("_+\" value=\"+1\" onclick=\"1\">\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t<form action=\"modify\" method=\"POST\">\r\n");
      out.write("\t\t\t<input type=\"button\" name=\"");
      out.print(id );
      out.write("_-\" value=\"-1\">\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t<form action=\"modify\" method=\"POST\">\r\n");
      out.write("\t\t\t<input type=\"button\" name=\"");
      out.print(id );
      out.write("_re\" value=\"削除\">\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<form action=\"\" method=\"get\">\r\n");
      out.write("\t\t\t<input type=\"submit\" name=\"b1\" value=\"button1\">\r\n");
      out.write("\t\t\t<input type=\"submit\" name=\"b2\" value=\"button2\">\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td align=\"right\">\\");
      out.print(exFormat.format(price) );
      out.write("</td>\r\n");
      out.write("\t\t<td align=\"center\">");
      out.print(exFormat.format(volume) );
      out.write("</td>\r\n");
      out.write("\t\t<td align=\"right\">\\");
      out.print(exFormat.format(anamount) );
      out.write("</td>\r\n");
      out.write("\t</tr>\r\n");

			amount += anamount;
		}

      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td align=\"center\" colspan=\"3\" style=\"font-weight:bold;\">小計</td>\r\n");
      out.write("\t\t<td align=\"right\" style=\"font-weight:bold;\">\\");
      out.print(exFormat.format(amount) );
      out.write("</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<p>\r\n");
      out.write("こちらでよろしければ、確認ボタンを押してください。\r\n");
      out.write("</p>\r\n");
      out.write("<form action=\"confirm\" method=\"POST\">\r\n");
      out.write("\t<input type=\"submit\" value=\"確認\">\r\n");
      out.write("</form>\r\n");
      out.write("<p></p>\r\n");
      out.write("<form action=\"search\" method=\"POST\">\r\n");
      out.write("\t<input type=\"submit\" value=\"他にもご注文の方はこちら>>\">\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
