/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.8
 * Generated at: 2014-06-23 03:18:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class test_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>JSP SAMPLE</title>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");

  out.println("※あなたが送信した内容<br>");
        
  String chk = request.getParameter("check1");
  String chk2 = chk == null ? "（check:未送信）" : chk;
  out.println("<font color=#FF0000>check:" + chk2 + "</font>");
        
  String radio = request.getParameter("radio1");
  radio = radio == null ? "（radio:未送信）" : radio;
  out.println("<font color=#FF0000>radio:" + radio + "</font>");
        

      out.write("\r\n");
      out.write("    <form method=\"post\" action=\"./test.jsp\">\r\n");
      out.write("      <label>\r\n");
      out.write("        <input type=\"checkbox\" name=\"check1\" value=\"check1\"\r\n");
      out.write("          ");
      out.print(chk != null ? "checked" : "" );
      out.write(">チェックボックス\r\n");
      out.write("      </label>\r\n");
      out.write("      <br>\r\n");
      out.write("      <label>\r\n");
      out.write("        <input type=\"radio\" name=\"radio1\" value=\"Windows\"\r\n");
      out.write("          ");
      out.print(radio.equals("Windows") ? "checked" : "" );
      out.write(">Windows\r\n");
      out.write("      </label>\r\n");
      out.write("      <label>\r\n");
      out.write("        <input type=\"radio\" name=\"radio1\" value=\"Linux\"\r\n");
      out.write("          ");
      out.print(radio.equals("Linux") ? "checked" : "" );
      out.write(">Linux\r\n");
      out.write("      </label>\r\n");
      out.write("      <label>\r\n");
      out.write("        <input type=\"radio\" name=\"radio1\" value=\"Mac OS\"\r\n");
      out.write("        ");
      out.print(radio.equals("Mac OS") ? "checked" : "" );
      out.write(">Mac OS\r\n");
      out.write("      </label>\r\n");
      out.write("      <input type=\"submit\">\r\n");
      out.write("    </form>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
